#!/bin/bash
# Universal Terraform Infrastructure Documentation Generator
# Works with any Terraform project and GitHub Actions

set -e

# Configuration
PROJECT_NAME="${PROJECT_NAME:-$(basename $(pwd))}"
ENVIRONMENT="${ENVIRONMENT:-${GITHUB_REF_NAME:-unknown}}"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
OUTPUT_DIR="./docs/infrastructure"
BRANCH_NAME="${GITHUB_REF_NAME:-$(git branch --show-current 2>/dev/null || echo 'local')}"

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "🚀 Generating Infrastructure Documentation for $PROJECT_NAME"
echo "📅 Timestamp: $TIMESTAMP"
echo "🌿 Branch: $BRANCH_NAME"
echo "🏗️ Environment: $ENVIRONMENT"

# 1. Generate Resource List
echo "📋 Generating resource inventory..."
terraform state list > "$OUTPUT_DIR/resources-list-$TIMESTAMP.txt" 2>/dev/null || echo "No state file found" > "$OUTPUT_DIR/resources-list-$TIMESTAMP.txt"

# 2. Generate Resource Summary
echo "📊 Generating resource summary..."
if terraform state list >/dev/null 2>&1; then
    terraform state list | cut -d. -f1 | sort | uniq -c | sort -nr > "$OUTPUT_DIR/resource-summary-$TIMESTAMP.txt"
else
    echo "No resources found in state" > "$OUTPUT_DIR/resource-summary-$TIMESTAMP.txt"
fi

# 3. Generate Outputs (if any)
echo "📤 Generating outputs..."
terraform output -json > "$OUTPUT_DIR/outputs-$TIMESTAMP.json" 2>/dev/null || echo "{}" > "$OUTPUT_DIR/outputs-$TIMESTAMP.json"

# 4. Generate Plan Summary (if in plan mode)
if [ "$1" = "plan" ]; then
    echo "📋 Generating plan summary..."
    terraform show -json tfplan 2>/dev/null | jq -r '.resource_changes[]? | "\(.change.actions[0]) \(.address)"' > "$OUTPUT_DIR/plan-changes-$TIMESTAMP.txt" || echo "No plan file found" > "$OUTPUT_DIR/plan-changes-$TIMESTAMP.txt"
fi

# 5. Generate Infrastructure Markdown Report
echo "📝 Generating infrastructure report..."
cat > "$OUTPUT_DIR/infrastructure-report-$TIMESTAMP.md" << EOF
# Infrastructure Report: $PROJECT_NAME

## Deployment Information
- **Project**: $PROJECT_NAME
- **Environment**: $ENVIRONMENT
- **Branch**: $BRANCH_NAME
- **Timestamp**: $TIMESTAMP
- **Terraform Version**: $(terraform version | head -n1)
- **Generated By**: GitHub Actions (Run #${GITHUB_RUN_NUMBER:-local})

## Resource Summary
\`\`\`
$(cat "$OUTPUT_DIR/resource-summary-$TIMESTAMP.txt")
\`\`\`

## Total Resources
**$(terraform state list 2>/dev/null | wc -l || echo 0)** resources deployed

## Outputs
\`\`\`json
$(cat "$OUTPUT_DIR/outputs-$TIMESTAMP.json")
\`\`\`

## Resource List
<details>
<summary>Click to expand full resource list</summary>

\`\`\`
$(cat "$OUTPUT_DIR/resources-list-$TIMESTAMP.txt")
\`\`\`
</details>

---
*Generated on $(date) by Terraform Infrastructure Documentation Generator*
EOF

# 6. Create/Update Latest Symlinks
echo "🔗 Creating latest file references..."
ln -sf "infrastructure-report-$TIMESTAMP.md" "$OUTPUT_DIR/infrastructure-report-latest.md"
ln -sf "resources-list-$TIMESTAMP.txt" "$OUTPUT_DIR/resources-list-latest.txt"
ln -sf "resource-summary-$TIMESTAMP.txt" "$OUTPUT_DIR/resource-summary-latest.txt"
ln -sf "outputs-$TIMESTAMP.json" "$OUTPUT_DIR/outputs-latest.json"

# 7. Generate Index File
echo "📚 Generating documentation index..."
cat > "$OUTPUT_DIR/README.md" << EOF
# Infrastructure Documentation

## Latest Deployment
- **Report**: [infrastructure-report-latest.md](./infrastructure-report-latest.md)
- **Resources**: [resources-list-latest.txt](./resources-list-latest.txt)
- **Summary**: [resource-summary-latest.txt](./resource-summary-latest.txt)
- **Outputs**: [outputs-latest.json](./outputs-latest.json)

## Historical Reports
$(ls -la "$OUTPUT_DIR"/infrastructure-report-*.md | grep -v latest | awk '{print "- [" $9 "](." $9 ")"}'  | head -10)

## Usage
This documentation is automatically generated after each Terraform deployment.
Files are timestamped and the latest versions are symlinked for easy access.

## Files Description
- \`infrastructure-report-*.md\`: Complete infrastructure report in Markdown
- \`resources-list-*.txt\`: List of all Terraform resources
- \`resource-summary-*.txt\`: Count of resources by type
- \`outputs-*.json\`: Terraform output values in JSON format
EOF

# 8. Cleanup old files (keep last 10)
echo "🧹 Cleaning up old documentation files..."
find "$OUTPUT_DIR" -name "infrastructure-report-*.md" -not -name "*latest*" | sort -r | tail -n +11 | xargs rm -f
find "$OUTPUT_DIR" -name "resources-list-*.txt" -not -name "*latest*" | sort -r | tail -n +11 | xargs rm -f
find "$OUTPUT_DIR" -name "resource-summary-*.txt" -not -name "*latest*" | sort -r | tail -n +11 | xargs rm -f
find "$OUTPUT_DIR" -name "outputs-*.json" -not -name "*latest*" | sort -r | tail -n +11 | xargs rm -f

echo ""
echo "✅ Infrastructure documentation generated successfully!"
echo "📁 Location: $OUTPUT_DIR/"
echo "📄 Latest report: $OUTPUT_DIR/infrastructure-report-latest.md"
echo "📊 Resource count: $(terraform state list 2>/dev/null | wc -l || echo 0)"
echo ""